require("plugin_configs.telescope")
require("plugin_configs.airline")
require("plugin_configs.palenight")
require("plugin_configs.bufferline")
require("plugin_configs.conform")
require("plugin_configs.indent_blankline")
require("plugin_configs.comment")
