require("plugin_configs.telescope")
require("plugin_configs.comment")
require("plugin_configs.nvimtree")
require("plugin_configs.catppuccin")
require("plugin_configs.lsp-config")
require("plugin_configs.barbar")
